# PRACTICE


CREATE DATABASE myDB;

USE myDB;

 CREATE TABLE ROLES (ID_ROL int NOT NULL, DESCRIP varchar(15), CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL));
 
  INSERT INTO ROLES VALUES (1, 'ADMIN');
  INSERT INTO ROLES VALUES (2,'ANON');
  INSERT INTO ROLES VALUES (3,'AUNTHENTICATED');
  
  CREATE TABLE USER(ID_USER int not null AUTO_INCREMENT, NAME varchar(25), ID_ROL int not null,
  CONSTRAINT PK_USER PRIMARY KEY (ID_USER), CONSTRAINT FK_ROLUSER FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL));
  
  ALTER TABLE USER ADD PASSWORD varchar(10) not null;
  ALTER TABLE USER ADD USER_NAME varchar(20) not null;
  
   CREATE VIEW ALLUSERS AS
    -> SELECT NAME, DESCRIP FROM USER INNER JOIN ROLES ON USER.ID_ROL = ROLES.ID_ROL;
