# PRACTICE


CREATE DATABASE myDB;

USE myDB;

 CREATE TABLE ROLES (ID_ROL int NOT NULL, DESCRIP varchar(15), CONSTRAINT PK_ROL PRIMARY KEY (ID_ROL));
 
  INSERT INTO ROLES VALUES (1, 'ADMIN');
  INSERT INTO ROLES VALUES (2,'ANON');
  INSERT INTO ROLES VALUES (3,'AUNTHENTICATED');
  
  CREATE TABLE USER(ID_USER int not null AUTO_INCREMENT, NAME varchar(25), ID_ROL int not null,
  CONSTRAINT PK_USER PRIMARY KEY (ID_USER), CONSTRAINT FK_ROLUSER FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID_ROL));
  
  ALTER TABLE USER ADD PASSWORD varchar(10) not null;
  ALTER TABLE USER ADD USER_NAME varchar(20) not null;
  
   CREATE VIEW ALLUSERS AS
    -> SELECT NAME, DESCRIP FROM USER INNER JOIN ROLES ON USER.ID_ROL = ROLES.ID_ROL;

 DELIMITER //
   CREATE PROCEDURE USERINS(nam varchar(25), idrol int, pass varchar(10), username varchar(20))
   BEGIN
   INSERT INTO USER (NAME,ID_ROL,PASSWORD,USER_NAME) VALUES (nam,idrol,pass,username);
   END//
   
    DELIMITER //
    CREATE PROCEDURE USEREDIT(id int, nam varchar (25), idrol int, pass varchar(10), username varchar(20))
    BEGIN
    UPDATE USER SET NAME = nam, ID_ROL = idrol, PASSWORD = pass, USER_NAME = username WHERE USER.ID_USER = id;
    END//
    
    DELIMITER //
     CREATE PROCEDURE USERDEL(iduser int)
     BEGIN
     DELETE FROM USER WHERE USER.ID_USER = iduser;
     END//
